language: objective-c
matrix:
  include:
    - osx_image: xcode11.6
      env: 'SIMULATOR="name=iPad Pro (12.9-inch) (2nd generation),OS=11.4"'

before_install:
  - xcrun simctl list
  - brew update || brew update
  - gem install bundler
install:
  - if [ -z "$(brew ls --versions coreutils)" ] ; then brew install coreutils ; fi
  - gem install xcpretty --no-document --quiet
script:
  - ./scripts/ci.sh "${SIMULATOR}"
